// @vitest-environment happy-dom
// Contract of the «QR tributario:» HEADING and the PLACE of the fiscal QR (sales#339).
//
// The AEAT's «Detalle de las especificaciones técnicas del código QR de la factura» v0.5.0 §3
// (published under Orden HAC/1177/2024 art. 21.1) says two things about the QR:
//   1. it is «always preceded» by the text «QR tributario:», placed ABOVE it (preferably centred),
//      in a type size equal to or larger than the rest of the invoice data;
//   2. it goes «at the beginning of the invoice, before the content generated by the invoicing
//      system», and if there are more QR codes the fiscal one comes first.
// The heading is its own field, `qr_heading` (the producer owns the legal text, the component only
// paints it), and the fiscal block opens the paper; the promotional QR stays at the foot.
import { beforeEach, describe, expect, it } from 'vitest';
import '../ok-receipt/ok-receipt.js';
import './ok-invoice.js';
import { OkReceipt, type ReceiptData } from '../ok-receipt/ok-receipt.js';
import { OkInvoice, type InvoiceData } from './ok-invoice.js';

const QR = 'https://prewww2.aeat.es/wlpl/TIKE-CONT/ValidarQR?nif=B1';

const RECEIPT: ReceiptData = {
  title: 'Factura simplificada',
  business: { name: 'MI NEGOCIO' },
  number: 'T-1',
  lines: [{ name: 'Cafe', qty: 1, unit_price: 180, total: 180 }],
  total: 180,
  qr: QR,
  qr_legend: 'VERI*FACTU',
  qr_note: 'CSV: ABC123',
  promo_qr: 'https://g.page/r/review',
};

const INVOICE: InvoiceData = {
  issuer: { name: 'MI NEGOCIO', tax_id: 'B12345678' },
  customer: { name: 'Cliente' },
  number: 'F-1',
  issue_date: '23/09/2026',
  lines: [{ description: 'Cafe', qty: 1, unit_price: 180, total: 180 }],
  subtotal: 180,
  taxes: [],
  tax_total: 0,
  total: 180,
  payment_method: 'Tarjeta',
  qr: QR,
  qr_legend: 'VERI*FACTU',
  qr_note: 'CSV: ABC123',
};

async function mountReceipt(receipt: ReceiptData): Promise<OkReceipt> {
  const el = document.createElement('ok-receipt') as OkReceipt;
  el.receipt = receipt;
  document.body.appendChild(el);
  await el.updateComplete;
  return el;
}

async function mountInvoice(invoice: InvoiceData): Promise<OkInvoice> {
  const el = document.createElement('ok-invoice') as OkInvoice;
  el.invoice = invoice;
  document.body.appendChild(el);
  await el.updateComplete;
  return el;
}

function cssOf(styles: unknown): string {
  return (Array.isArray(styles) ? styles : [styles]).map((s) => String(s)).join('\n');
}

/** Font size in px of `selector` in the component CSS (first declaration found). */
function fontSize(styles: unknown, selector: string): number {
  const esc = selector.replace('.', '\\.');
  const m = cssOf(styles).match(new RegExp(`${esc}\\s*\\{[^}]*font-size:\\s*(\\d+(?:\\.\\d+)?)px`));
  return m ? Number(m[1]) : NaN;
}

function blockOrder(wrap: Element): string[] {
  return [...wrap.children].map((c) => (c.tagName.toLowerCase() === 'ok-qr' ? 'qr' : c.className));
}

beforeEach(() => { document.body.innerHTML = ''; });

describe.each([
  ['ok-receipt', '.paper', () => mountReceipt({ ...RECEIPT, qr_heading: 'QR tributario:' }), () => mountReceipt(RECEIPT),
    () => mountReceipt({ ...RECEIPT, qr: undefined, qr_heading: 'QR tributario:' })],
  ['ok-invoice', '.sheet', () => mountInvoice({ ...INVOICE, qr_heading: 'QR tributario:' }), () => mountInvoice(INVOICE),
    () => mountInvoice({ ...INVOICE, qr: undefined, qr_heading: 'QR tributario:' })],
] as const)('%s — qr_heading and the fiscal QR first', (_tag, root, withHeading, withoutHeading, withoutQr) => {
  it('paints «QR tributario:» ABOVE the fiscal QR, with the legend and the note under it', async () => {
    const el = await withHeading();
    const wrap = el.shadowRoot!.querySelector('.qr-wrap')!;
    expect(blockOrder(wrap)).toEqual(['qr-heading', 'qr', 'qr-legend', 'qr-note']);
    expect(wrap.querySelector('.qr-heading')!.textContent).toBe('QR tributario:');
  });

  it('opens the document with the fiscal QR, before anything else the system writes', async () => {
    const el = await withHeading();
    const paper = el.shadowRoot!.querySelector(root)!;
    expect(paper.firstElementChild!.classList.contains('qr-wrap')).toBe(true);
  });

  it('keeps the fiscal QR first even when the producer does not send the heading yet', async () => {
    const el = await withoutHeading();
    const paper = el.shadowRoot!.querySelector(root)!;
    expect(paper.firstElementChild!.classList.contains('qr-wrap')).toBe(true);
    expect(el.shadowRoot!.querySelector('.qr-heading')).toBeNull();
  });

  it('without the fiscal QR there is no heading: it would announce a code that is not there', async () => {
    const el = await withoutQr();
    expect(el.shadowRoot!.querySelector('.qr-heading')).toBeNull();
    expect(el.shadowRoot!.querySelector('.qr-wrap')).toBeNull();
  });
});

describe('ok-receipt — the promotional QR stays at the foot', () => {
  it('is the last block of the paper, after the fiscal one', async () => {
    const el = await mountReceipt({ ...RECEIPT, qr_heading: 'QR tributario:' });
    const paper = el.shadowRoot!.querySelector('.paper')!;
    expect(paper.lastElementChild!.classList.contains('promo-wrap')).toBe(true);
  });
});

describe('ok-invoice — the payment box stays in the foot without the QR', () => {
  it('still paints the payment method at the foot', async () => {
    const el = await mountInvoice({ ...INVOICE, qr_heading: 'QR tributario:' });
    const foot = el.shadowRoot!.querySelector('.foot')!;
    expect(foot.textContent).toContain('Tarjeta');
    expect(foot.querySelector('ok-qr')).toBeNull();
  });
});

describe('qr_heading — type size equal to or larger than the data (AEAT QR spec v0.5.0 §3)', () => {
  it('ok-receipt paints it at least as large as the ticket body text (11px)', () => {
    expect(fontSize(OkReceipt.styles, '.qr-heading')).toBeGreaterThanOrEqual(11);
  });

  it('ok-invoice paints it at least as large as the invoice body text', () => {
    expect(fontSize(OkInvoice.styles, '.qr-heading')).toBeGreaterThanOrEqual(fontSize(OkInvoice.styles, '.sheet'));
  });
});
